import { readdir, readFile, writeFile } from 'fs/promises';
import { join, dirname } from 'path';
import { createCanvas, loadImage } from 'canvas';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const TEXTURE_DIR = join(__dirname, 'block');
const OUTPUT_FILE = join(__dirname, 'blockColorsGenerated.js');

const BLOCK_NAME_MAPPING = {
  'stone': 'minecraft:stone',
  'granite': 'minecraft:granite',
  'diorite': 'minecraft:diorite',
  'andesite': 'minecraft:andesite',
  'grass_block_top': 'minecraft:grass_block',
  'grass_block_side': 'minecraft:grass_block',
  'dirt': 'minecraft:dirt',
  'coarse_dirt': 'minecraft:coarse_dirt',
  'podzol_top': 'minecraft:podzol',
  'cobblestone': 'minecraft:cobblestone',
  'oak_planks': 'minecraft:oak_planks',
  'spruce_planks': 'minecraft:spruce_planks',
  'birch_planks': 'minecraft:birch_planks',
  'jungle_planks': 'minecraft:jungle_planks',
  'acacia_planks': 'minecraft:acacia_planks',
  'dark_oak_planks': 'minecraft:dark_oak_planks',
  'oak_log': 'minecraft:oak_log',
  'oak_log_top': 'minecraft:oak_log',
  'spruce_log': 'minecraft:spruce_log',
  'spruce_log_top': 'minecraft:spruce_log',
  'birch_log': 'minecraft:birch_log',
  'birch_log_top': 'minecraft:birch_log',
  'jungle_log': 'minecraft:jungle_log',
  'jungle_log_top': 'minecraft:jungle_log',
  'acacia_log': 'minecraft:acacia_log',
  'acacia_log_top': 'minecraft:acacia_log',
  'dark_oak_log': 'minecraft:dark_oak_log',
  'dark_oak_log_top': 'minecraft:dark_oak_log',
  'mangrove_log': 'minecraft:mangrove_log',
  'mangrove_log_top': 'minecraft:mangrove_log',
  'cherry_log': 'minecraft:cherry_log',
  'cherry_log_top': 'minecraft:cherry_log',
  'oak_leaves': 'minecraft:oak_leaves',
  'spruce_leaves': 'minecraft:spruce_leaves',
  'birch_leaves': 'minecraft:birch_leaves',
  'jungle_leaves': 'minecraft:jungle_leaves',
  'acacia_leaves': 'minecraft:acacia_leaves',
  'dark_oak_leaves': 'minecraft:dark_oak_leaves',
  'mangrove_leaves': 'minecraft:mangrove_leaves',
  'cherry_leaves': 'minecraft:cherry_leaves',
  'azalea_leaves': 'minecraft:azalea_leaves',
  'flowering_azalea_leaves': 'minecraft:flowering_azalea_leaves',
  'sand': 'minecraft:sand',
  'red_sand': 'minecraft:red_sand',
  'gravel': 'minecraft:gravel',
  'gold_ore': 'minecraft:gold_ore',
  'iron_ore': 'minecraft:iron_ore',
  'coal_ore': 'minecraft:coal_ore',
  'diamond_ore': 'minecraft:diamond_ore',
  'emerald_ore': 'minecraft:emerald_ore',
  'lapis_ore': 'minecraft:lapis_ore',
  'redstone_ore': 'minecraft:redstone_ore',
  'copper_ore': 'minecraft:copper_ore',
  'deepslate': 'minecraft:deepslate',
  'deepslate_gold_ore': 'minecraft:deepslate_gold_ore',
  'deepslate_iron_ore': 'minecraft:deepslate_iron_ore',
  'deepslate_coal_ore': 'minecraft:deepslate_coal_ore',
  'deepslate_diamond_ore': 'minecraft:deepslate_diamond_ore',
  'deepslate_emerald_ore': 'minecraft:deepslate_emerald_ore',
  'deepslate_lapis_ore': 'minecraft:deepslate_lapis_ore',
  'deepslate_redstone_ore': 'minecraft:deepslate_redstone_ore',
  'deepslate_copper_ore': 'minecraft:deepslate_copper_ore',
  'bedrock': 'minecraft:bedrock',
  'water': 'minecraft:water',
  'lava': 'minecraft:lava',
  'sandstone_top': 'minecraft:sandstone',
  'sandstone': 'minecraft:sandstone',
  'red_sandstone_top': 'minecraft:red_sandstone',
  'red_sandstone': 'minecraft:red_sandstone',
  'snow': 'minecraft:snow_block',
  'ice': 'minecraft:ice',
  'blue_ice': 'minecraft:blue_ice',
  'packed_ice': 'minecraft:packed_ice',
  'obsidian': 'minecraft:obsidian',
  'netherrack': 'minecraft:netherrack',
  'glowstone': 'minecraft:glowstone',
  'nether_bricks': 'minecraft:nether_bricks',
  'end_stone': 'minecraft:end_stone',
  'purpur_block': 'minecraft:purpur_block',
  'purpur_pillar_top': 'minecraft:purpur_pillar',
  'prismarine': 'minecraft:prismarine',
  'dark_prismarine': 'minecraft:dark_prismarine',
  'prismarine_bricks': 'minecraft:prismarine_bricks',
  'sea_lantern': 'minecraft:sea_lantern',
  'hay_block_top': 'minecraft:hay_block',
  'hay_block_side': 'minecraft:hay_block',
  'terracotta': 'minecraft:terracotta',
  'white_terracotta': 'minecraft:white_terracotta',
  'orange_terracotta': 'minecraft:orange_terracotta',
  'magenta_terracotta': 'minecraft:magenta_terracotta',
  'light_blue_terracotta': 'minecraft:light_blue_terracotta',
  'yellow_terracotta': 'minecraft:yellow_terracotta',
  'lime_terracotta': 'minecraft:lime_terracotta',
  'pink_terracotta': 'minecraft:pink_terracotta',
  'gray_terracotta': 'minecraft:gray_terracotta',
  'light_gray_terracotta': 'minecraft:light_gray_terracotta',
  'cyan_terracotta': 'minecraft:cyan_terracotta',
  'purple_terracotta': 'minecraft:purple_terracotta',
  'blue_terracotta': 'minecraft:blue_terracotta',
  'brown_terracotta': 'minecraft:brown_terracotta',
  'green_terracotta': 'minecraft:green_terracotta',
  'red_terracotta': 'minecraft:red_terracotta',
  'black_terracotta': 'minecraft:black_terracotta',
  'white_wool': 'minecraft:white_wool',
  'orange_wool': 'minecraft:orange_wool',
  'magenta_wool': 'minecraft:magenta_wool',
  'light_blue_wool': 'minecraft:light_blue_wool',
  'yellow_wool': 'minecraft:yellow_wool',
  'lime_wool': 'minecraft:lime_wool',
  'pink_wool': 'minecraft:pink_wool',
  'gray_wool': 'minecraft:gray_wool',
  'light_gray_wool': 'minecraft:light_gray_wool',
  'cyan_wool': 'minecraft:cyan_wool',
  'purple_wool': 'minecraft:purple_wool',
  'blue_wool': 'minecraft:blue_wool',
  'brown_wool': 'minecraft:brown_wool',
  'green_wool': 'minecraft:green_wool',
  'red_wool': 'minecraft:red_wool',
  'black_wool': 'minecraft:black_wool',
  'white_concrete': 'minecraft:white_concrete',
  'orange_concrete': 'minecraft:orange_concrete',
  'magenta_concrete': 'minecraft:magenta_concrete',
  'light_blue_concrete': 'minecraft:light_blue_concrete',
  'yellow_concrete': 'minecraft:yellow_concrete',
  'lime_concrete': 'minecraft:lime_concrete',
  'pink_concrete': 'minecraft:pink_concrete',
  'gray_concrete': 'minecraft:gray_concrete',
  'light_gray_concrete': 'minecraft:light_gray_concrete',
  'cyan_concrete': 'minecraft:cyan_concrete',
  'purple_concrete': 'minecraft:purple_concrete',
  'blue_concrete': 'minecraft:blue_concrete',
  'brown_concrete': 'minecraft:brown_concrete',
  'green_concrete': 'minecraft:green_concrete',
  'red_concrete': 'minecraft:red_concrete',
  'black_concrete': 'minecraft:black_concrete',
  'bricks': 'minecraft:bricks',
  'bookshelf': 'minecraft:bookshelf',
  'mossy_cobblestone': 'minecraft:mossy_cobblestone',
  'moss_block': 'minecraft:moss_block',
  'moss_carpet': 'minecraft:moss_carpet',
  'stone_bricks': 'minecraft:stone_bricks',
  'mossy_stone_bricks': 'minecraft:mossy_stone_bricks',
  'cracked_stone_bricks': 'minecraft:cracked_stone_bricks',
  'chiseled_stone_bricks': 'minecraft:chiseled_stone_bricks',
  'tnt_side': 'minecraft:tnt',
  'tnt_top': 'minecraft:tnt',
  'tnt_bottom': 'minecraft:tnt',
  'pumpkin_top': 'minecraft:pumpkin',
  'pumpkin_side': 'minecraft:pumpkin',
  'carved_pumpkin': 'minecraft:carved_pumpkin',
  'jack_o_lantern': 'minecraft:jack_o_lantern',
  'melon_top': 'minecraft:melon',
  'melon_side': 'minecraft:melon',
  'mycelium_top': 'minecraft:mycelium',
  'mycelium_side': 'minecraft:mycelium',
  'clay': 'minecraft:clay',
  'dried_kelp_top': 'minecraft:dried_kelp_block',
  'dried_kelp_side': 'minecraft:dried_kelp_block',
  'dried_kelp_bottom': 'minecraft:dried_kelp_block',
  'bamboo_block': 'minecraft:bamboo_block',
  'bamboo_planks': 'minecraft:bamboo_planks',
  'bamboo_mosaic': 'minecraft:bamboo_mosaic',
  'cherry_planks': 'minecraft:cherry_planks',
  'mangrove_planks': 'minecraft:mangrove_planks',
  'crimson_planks': 'minecraft:crimson_planks',
  'warped_planks': 'minecraft:warped_planks',
  'crimson_stem': 'minecraft:crimson_stem',
  'crimson_stem_top': 'minecraft:crimson_stem',
  'warped_stem': 'minecraft:warped_stem',
  'warped_stem_top': 'minecraft:warped_stem',
  'crimson_nylium': 'minecraft:crimson_nylium',
  'warped_nylium': 'minecraft:warped_nylium',
  'basalt_top': 'minecraft:basalt',
  'basalt_side': 'minecraft:basalt',
  'blackstone': 'minecraft:blackstone',
  'blackstone_top': 'minecraft:blackstone',
  'gilded_blackstone': 'minecraft:gilded_blackstone',
  'crying_obsidian': 'minecraft:crying_obsidian',
  'ancient_debris_top': 'minecraft:ancient_debris',
  'ancient_debris_side': 'minecraft:ancient_debris',
  'copper_block': 'minecraft:copper_block',
  'exposed_copper': 'minecraft:exposed_copper',
  'weathered_copper': 'minecraft:weathered_copper',
  'oxidized_copper': 'minecraft:oxidized_copper',
  'cut_copper': 'minecraft:cut_copper',
  'exposed_cut_copper': 'minecraft:exposed_cut_copper',
  'chiseled_copper': 'minecraft:chiseled_copper',
  'copper_grate': 'minecraft:copper_grate',
  'exposed_copper_grate': 'minecraft:exposed_copper_grate',
  'copper_bulb': 'minecraft:copper_bulb',
  'exposed_copper_bulb': 'minecraft:exposed_copper_bulb',
  'amethyst_block': 'minecraft:amethyst_block',
  'budding_amethyst': 'minecraft:budding_amethyst',
  'calcite': 'minecraft:calcite',
  'tuff': 'minecraft:tuff',
  'chiseled_tuff': 'minecraft:chiseled_tuff',
  'tuff_bricks': 'minecraft:tuff_bricks',
  'chiseled_tuff_bricks': 'minecraft:chiseled_tuff_bricks',
  'dripstone_block': 'minecraft:dripstone_block',
  'sculk': 'minecraft:sculk',
  'sculk_sensor_top': 'minecraft:sculk_sensor',
  'calibrated_sculk_sensor_top': 'minecraft:calibrated_sculk_sensor',
  'deepslate_bricks': 'minecraft:deepslate_bricks',
  'deepslate_tiles': 'minecraft:deepslate_tiles',
  'chiseled_deepslate': 'minecraft:chiseled_deepslate',
  'cobbled_deepslate': 'minecraft:cobbled_deepslate',
  'polished_deepslate': 'minecraft:polished_deepslate',
  'mud': 'minecraft:mud',
  'mud_bricks': 'minecraft:mud_bricks',
  'packed_mud': 'minecraft:packed_mud',
  'frogspawn': 'minecraft:frogspawn',
  'mangrove_roots_top': 'minecraft:mangrove_roots',
  'mangrove_roots_side': 'minecraft:mangrove_roots',
  'muddy_mangrove_roots_top': 'minecraft:muddy_mangrove_roots',
  'muddy_mangrove_roots_side': 'minecraft:muddy_mangrove_roots',
  'reinforced_deepslate_top': 'minecraft:reinforced_deepslate',
  'reinforced_deepslate_side': 'minecraft:reinforced_deepslate',
  'sculk_catalyst_top': 'minecraft:sculk_catalyst',
  'sculk_catalyst_side': 'minecraft:sculk_catalyst',
  'sculk_shrieker_top': 'minecraft:sculk_shrieker',
  'sculk_shrieker_side': 'minecraft:sculk_shrieker',
  'sculk_vein': 'minecraft:sculk_vein',
  'bone_block_top': 'minecraft:bone_block',
  'bone_block_side': 'minecraft:bone_block',
  'quartz_block_top': 'minecraft:quartz_block',
  'quartz_block_side': 'minecraft:quartz_block',
  'chiseled_quartz_block': 'minecraft:chiseled_quartz_block',
  'chiseled_quartz_block_top': 'minecraft:chiseled_quartz_block',
  'quartz_pillar_top': 'minecraft:quartz_pillar',
  'quartz_pillar': 'minecraft:quartz_pillar',
  'smooth_quartz': 'minecraft:smooth_quartz',
  'nether_gold_ore': 'minecraft:nether_gold_ore',
  'soul_sand': 'minecraft:soul_sand',
  'soul_soil': 'minecraft:soul_soil',
  'shroomlight': 'minecraft:shroomlight',
  'nether_wart_block': 'minecraft:nether_wart_block',
  'warped_wart_block': 'minecraft:warped_wart_block',
  'beacon': 'minecraft:beacon',
  'conduit': 'minecraft:conduit',
  'end_portal_frame_top': 'minecraft:end_portal_frame',
  'end_portal_frame_side': 'minecraft:end_portal_frame',
  'end_portal_frame_eye': 'minecraft:end_portal_frame',
  'dragon_egg': 'minecraft:dragon_egg',
  'redstone_lamp': 'minecraft:redstone_lamp',
  'redstone_lamp_on': 'minecraft:redstone_lamp',
  'slime_block': 'minecraft:slime_block',
  'honey_block_top': 'minecraft:honey_block',
  'honey_block_side': 'minecraft:honey_block',
  'honey_block_bottom': 'minecraft:honey_block',
  'honeycomb_block': 'minecraft:honeycomb_block',
  'cactus_top': 'minecraft:cactus',
  'cactus_side': 'minecraft:cactus',
  'cactus_bottom': 'minecraft:cactus',
  'vine': 'minecraft:vine',
  'lily_pad': 'minecraft:lily_pad',
  'rose_bush_top': 'minecraft:rose_bush',
  'rose_bush_bottom': 'minecraft:rose_bush',
  'peony_top': 'minecraft:peony',
  'peony_bottom': 'minecraft:peony',
  'lilac_top': 'minecraft:lilac',
  'lilac_bottom': 'minecraft:lilac',
  'sunflower_top': 'minecraft:sunflower',
  'sunflower_bottom': 'minecraft:sunflower',
  'dandelion': 'minecraft:dandelion',
  'poppy': 'minecraft:poppy',
  'blue_orchid': 'minecraft:blue_orchid',
  'allium': 'minecraft:allium',
  'azure_bluet': 'minecraft:azure_bluet',
  'red_tulip': 'minecraft:red_tulip',
  'orange_tulip': 'minecraft:orange_tulip',
  'white_tulip': 'minecraft:white_tulip',
  'pink_tulip': 'minecraft:pink_tulip',
  'oxeye_daisy': 'minecraft:oxeye_daisy',
  'cornflower': 'minecraft:cornflower',
  'lily_of_the_valley': 'minecraft:lily_of_the_valley',
  'wither_rose': 'minecraft:wither_rose',
  'spore_blossom': 'minecraft:spore_blossom',
  'torchflower': 'minecraft:torchflower',
  'pitcher_plant': 'minecraft:pitcher_plant',
  'pink_petals': 'minecraft:pink_petals',
  'dripleaf_top': 'minecraft:big_dripleaf',
  'big_dripleaf_top': 'minecraft:big_dripleaf',
  'big_dripleaf_side': 'minecraft:big_dripleaf',
  'small_dripleaf_top': 'minecraft:small_dripleaf',
  'hanging_roots': 'minecraft:hanging_roots',
  'rooted_dirt': 'minecraft:rooted_dirt',
  'azalea_top': 'minecraft:azalea',
  'flowering_azalea_top': 'minecraft:flowering_azalea',
  'glass': 'minecraft:glass',
  'glass_pane_top': 'minecraft:glass_pane',
  'white_stained_glass': 'minecraft:white_stained_glass',
  'orange_stained_glass': 'minecraft:orange_stained_glass',
  'magenta_stained_glass': 'minecraft:magenta_stained_glass',
  'light_blue_stained_glass': 'minecraft:light_blue_stained_glass',
  'yellow_stained_glass': 'minecraft:yellow_stained_glass',
  'lime_stained_glass': 'minecraft:lime_stained_glass',
  'pink_stained_glass': 'minecraft:pink_stained_glass',
  'gray_stained_glass': 'minecraft:gray_stained_glass',
  'light_gray_stained_glass': 'minecraft:light_gray_stained_glass',
  'cyan_stained_glass': 'minecraft:cyan_stained_glass',
  'purple_stained_glass': 'minecraft:purple_stained_glass',
  'blue_stained_glass': 'minecraft:blue_stained_glass',
  'brown_stained_glass': 'minecraft:brown_stained_glass',
  'green_stained_glass': 'minecraft:green_stained_glass',
  'red_stained_glass': 'minecraft:red_stained_glass',
  'black_stained_glass': 'minecraft:black_stained_glass',
  'iron_block': 'minecraft:iron_block',
  'gold_block': 'minecraft:gold_block',
  'diamond_block': 'minecraft:diamond_block',
  'emerald_block': 'minecraft:emerald_block',
  'lapis_block': 'minecraft:lapis_block',
  'coal_block': 'minecraft:coal_block',
  'redstone_block': 'minecraft:redstone_block',
  'netherite_block': 'minecraft:netherite_block',
  'raw_iron_block': 'minecraft:raw_iron_block',
  'raw_gold_block': 'minecraft:raw_gold_block',
  'raw_copper_block': 'minecraft:raw_copper_block',
  'crafting_table_top': 'minecraft:crafting_table',
  'crafting_table_front': 'minecraft:crafting_table',
  'crafting_table_side': 'minecraft:crafting_table',
  'furnace_top': 'minecraft:furnace',
  'furnace_front': 'minecraft:furnace',
  'furnace_side': 'minecraft:furnace',
  'blast_furnace_top': 'minecraft:blast_furnace',
  'blast_furnace_front': 'minecraft:blast_furnace',
  'blast_furnace_side': 'minecraft:blast_furnace',
  'smoker_top': 'minecraft:smoker',
  'smoker_front': 'minecraft:smoker',
  'smoker_side': 'minecraft:smoker',
  'enchanting_table_top': 'minecraft:enchanting_table',
  'enchanting_table_side': 'minecraft:enchanting_table',
  'anvil_top': 'minecraft:anvil',
  'anvil': 'minecraft:anvil',
  'chipped_anvil_top': 'minecraft:chipped_anvil',
  'damaged_anvil_top': 'minecraft:damaged_anvil',
  'smithing_table_top': 'minecraft:smithing_table',
  'fletching_table_top': 'minecraft:fletching_table',
  'cartography_table_top': 'minecraft:cartography_table',
  'loom_top': 'minecraft:loom',
  'barrel_top': 'minecraft:barrel',
  'barrel_side': 'minecraft:barrel',
  'lectern_top': 'minecraft:lectern',
  'stonecutter_top': 'minecraft:stonecutter',
  'grindstone_top': 'minecraft:grindstone',
  'composter_top': 'minecraft:composter',
  'composter_side': 'minecraft:composter',
  'bell_top': 'minecraft:bell',
  'bell_side': 'minecraft:bell',
  'lantern': 'minecraft:lantern',
  'soul_lantern': 'minecraft:soul_lantern',
  'campfire_log': 'minecraft:campfire',
  'soul_campfire_log': 'minecraft:soul_campfire',
  'bee_nest_top': 'minecraft:bee_nest',
  'bee_nest_front': 'minecraft:bee_nest',
  'bee_nest_side': 'minecraft:bee_nest',
  'beehive_top': 'minecraft:beehive',
  'beehive_front': 'minecraft:beehive',
  'beehive_side': 'minecraft:beehive',
  'lodestone_top': 'minecraft:lodestone',
  'lodestone_side': 'minecraft:lodestone',
  'respawn_anchor_top': 'minecraft:respawn_anchor',
  'respawn_anchor_side': 'minecraft:respawn_anchor',
  'target_top': 'minecraft:target',
  'target_side': 'minecraft:target',
  'lightning_rod': 'minecraft:lightning_rod',
  'candle': 'minecraft:candle',
  'white_candle': 'minecraft:white_candle',
  'orange_candle': 'minecraft:orange_candle',
  'magenta_candle': 'minecraft:magenta_candle',
  'light_blue_candle': 'minecraft:light_blue_candle',
  'yellow_candle': 'minecraft:yellow_candle',
  'lime_candle': 'minecraft:lime_candle',
  'pink_candle': 'minecraft:pink_candle',
  'gray_candle': 'minecraft:gray_candle',
  'light_gray_candle': 'minecraft:light_gray_candle',
  'cyan_candle': 'minecraft:cyan_candle',
  'purple_candle': 'minecraft:purple_candle',
  'blue_candle': 'minecraft:blue_candle',
  'brown_candle': 'minecraft:brown_candle',
  'green_candle': 'minecraft:green_candle',
  'red_candle': 'minecraft:red_candle',
  'black_candle': 'minecraft:black_candle',
  'small_amethyst_bud': 'minecraft:small_amethyst_bud',
  'medium_amethyst_bud': 'minecraft:medium_amethyst_bud',
  'large_amethyst_bud': 'minecraft:large_amethyst_bud',
  'amethyst_cluster': 'minecraft:amethyst_cluster',
  'pointed_dripstone': 'minecraft:pointed_dripstone',
  'sugar_cane': 'minecraft:sugar_cane',
  'bamboo_stalk': 'minecraft:bamboo',
  'bamboo_singleleaf': 'minecraft:bamboo',
  'bamboo_large_leaves': 'minecraft:bamboo',
  'bamboo_small_leaves': 'minecraft:bamboo',
  'kelp': 'minecraft:kelp',
  'kelp_plant': 'minecraft:kelp_plant',
  'seagrass': 'minecraft:seagrass',
  'tall_seagrass_top': 'minecraft:tall_seagrass',
  'tall_seagrass_bottom': 'minecraft:tall_seagrass',
  'dead_bush': 'minecraft:dead_bush',
  'fern': 'minecraft:fern',
  'tall_grass_top': 'minecraft:tall_grass',
  'grass': 'minecraft:grass',
  'crimson_roots': 'minecraft:crimson_roots',
  'warped_roots': 'minecraft:warped_roots',
  'nether_sprouts': 'minecraft:nether_sprouts',
  'weeping_vines': 'minecraft:weeping_vines',
  'twisting_vines': 'minecraft:twisting_vines',
  'chorus_flower': 'minecraft:chorus_flower',
  'chorus_plant': 'minecraft:chorus_plant',
  'brown_mushroom': 'minecraft:brown_mushroom',
  'red_mushroom': 'minecraft:red_mushroom',
  'brown_mushroom_block': 'minecraft:brown_mushroom_block',
  'red_mushroom_block': 'minecraft:red_mushroom_block',
  'mushroom_stem': 'minecraft:mushroom_stem',
  'crimson_fungus': 'minecraft:crimson_fungus',
  'warped_fungus': 'minecraft:warped_fungus',
  'wheat_stage0': 'minecraft:wheat',
  'wheat_stage7': 'minecraft:wheat',
  'carrots_stage3': 'minecraft:carrots',
  'potatoes_stage3': 'minecraft:potatoes',
  'beetroots_stage3': 'minecraft:beetroots',
  'melon_stem': 'minecraft:melon_stem',
  'pumpkin_stem': 'minecraft:pumpkin_stem',
  'cocoa_stage2': 'minecraft:cocoa',
  'nether_wart_stage2': 'minecraft:nether_wart',
  'sweet_berry_bush_stage3': 'minecraft:sweet_berry_bush',
  'cave_vines': 'minecraft:cave_vines',
  'cave_vines_lit': 'minecraft:cave_vines',
  'glow_lichen': 'minecraft:glow_lichen',
  'fire_0': 'minecraft:fire',
  'soul_fire_0': 'minecraft:soul_fire',
  'rail': 'minecraft:rail',
  'powered_rail': 'minecraft:powered_rail',
  'detector_rail': 'minecraft:detector_rail',
  'activator_rail': 'minecraft:activator_rail',
  'redstone_dust_dot': 'minecraft:redstone_wire',
  'repeater': 'minecraft:repeater',
  'comparator': 'minecraft:comparator',
  'lever': 'minecraft:lever',
  'stone_button': 'minecraft:stone_button',
  'oak_button': 'minecraft:oak_button',
  'oak_pressure_plate': 'minecraft:oak_pressure_plate',
  'stone_pressure_plate': 'minecraft:stone_pressure_plate',
  'heavy_weighted_pressure_plate': 'minecraft:heavy_weighted_pressure_plate',
  'light_weighted_pressure_plate': 'minecraft:light_weighted_pressure_plate',
  'oak_door_bottom': 'minecraft:oak_door',
  'oak_door_top': 'minecraft:oak_door',
  'iron_door_bottom': 'minecraft:iron_door',
  'iron_door_top': 'minecraft:iron_door',
  'oak_trapdoor': 'minecraft:oak_trapdoor',
  'iron_trapdoor': 'minecraft:iron_trapdoor',
  'oak_fence': 'minecraft:oak_fence',
  'oak_fence_gate': 'minecraft:oak_fence_gate',
  'ladder': 'minecraft:ladder',
  'chest': 'minecraft:chest',
  'ender_chest': 'minecraft:ender_chest',
  'trapped_chest': 'minecraft:trapped_chest',
  'shulker_box': 'minecraft:shulker_box',
  'white_shulker_box': 'minecraft:white_shulker_box',
  'black_shulker_box': 'minecraft:black_shulker_box',
  'barrel': 'minecraft:barrel',
  'smoker': 'minecraft:smoker',
  'blast_furnace': 'minecraft:blast_furnace',
  'dispenser_front': 'minecraft:dispenser',
  'dropper_front': 'minecraft:dropper',
  'hopper_top': 'minecraft:hopper',
  'hopper_side': 'minecraft:hopper',
  'chain_command_block_front': 'minecraft:chain_command_block',
  'repeating_command_block_front': 'minecraft:repeating_command_block',
  'command_block_front': 'minecraft:command_block',
  'structure_block': 'minecraft:structure_block',
  'jigsaw_top': 'minecraft:jigsaw',
  'scaffolding_top': 'minecraft:scaffolding',
  'scaffolding_side': 'minecraft:scaffolding',
  'cobweb': 'minecraft:cobweb',
  'flower_pot': 'minecraft:flower_pot',
  'skeleton_skull': 'minecraft:skeleton_skull',
  'wither_skeleton_skull': 'minecraft:wither_skeleton_skull',
  'zombie_head': 'minecraft:zombie_head',
  'player_head': 'minecraft:player_head',
  'creeper_head': 'minecraft:creeper_head',
  'dragon_head': 'minecraft:dragon_head',
  'piglin_head': 'minecraft:piglin_head',
  'sniffer_egg': 'minecraft:sniffer_egg',
  'turtle_egg': 'minecraft:turtle_egg',
  'frogspawn': 'minecraft:frogspawn',
  'trial_spawner_top': 'minecraft:trial_spawner',
  'vault_top': 'minecraft:vault',
  'crafter_top': 'minecraft:crafter',
  'crafter_side': 'minecraft:crafter',
  'decorated_pot_top': 'minecraft:decorated_pot',
  'decorated_pot_side': 'minecraft:decorated_pot',
  'chiseled_bookshelf_top': 'minecraft:chiseled_bookshelf',
  'chiseled_bookshelf_side': 'minecraft:chiseled_bookshelf',
  'white_carpet': 'minecraft:white_carpet',
  'orange_carpet': 'minecraft:orange_carpet',
  'magenta_carpet': 'minecraft:magenta_carpet',
  'light_blue_carpet': 'minecraft:light_blue_carpet',
  'yellow_carpet': 'minecraft:yellow_carpet',
  'lime_carpet': 'minecraft:lime_carpet',
  'pink_carpet': 'minecraft:pink_carpet',
  'gray_carpet': 'minecraft:gray_carpet',
  'light_gray_carpet': 'minecraft:light_gray_carpet',
  'cyan_carpet': 'minecraft:cyan_carpet',
  'purple_carpet': 'minecraft:purple_carpet',
  'blue_carpet': 'minecraft:blue_carpet',
  'brown_carpet': 'minecraft:brown_carpet',
  'green_carpet': 'minecraft:green_carpet',
  'red_carpet': 'minecraft:red_carpet',
  'black_carpet': 'minecraft:black_carpet',
  'moss_carpet': 'minecraft:moss_carpet',
  'farmland': 'minecraft:farmland',
  'farmland_moist': 'minecraft:farmland',
  'dirt_path_top': 'minecraft:dirt_path',
  'dirt_path_side': 'minecraft:dirt_path',
  'attached_pumpkin_stem': 'minecraft:pumpkin_stem',
  'attached_melon_stem': 'minecraft:melon_stem',
  'brain_coral': 'minecraft:brain_coral',
  'bubble_coral': 'minecraft:bubble_coral',
  'fire_coral': 'minecraft:fire_coral',
  'horn_coral': 'minecraft:horn_coral',
  'tube_coral': 'minecraft:tube_coral',
  'brain_coral_block': 'minecraft:brain_coral_block',
  'bubble_coral_block': 'minecraft:bubble_coral_block',
  'fire_coral_block': 'minecraft:fire_coral_block',
  'horn_coral_block': 'minecraft:horn_coral_block',
  'tube_coral_block': 'minecraft:tube_coral_block',
  'dead_brain_coral': 'minecraft:dead_brain_coral',
  'dead_bubble_coral': 'minecraft:dead_bubble_coral',
  'dead_fire_coral': 'minecraft:dead_fire_coral',
  'dead_horn_coral': 'minecraft:dead_horn_coral',
  'dead_tube_coral': 'minecraft:dead_tube_coral',
  'sea_pickle': 'minecraft:sea_pickle',
  'turtle_egg': 'minecraft:turtle_egg',
  'conduit': 'minecraft:conduit',
  'bubble_column': 'minecraft:bubble_column',
  'kelp': 'minecraft:kelp',
  'seagrass': 'minecraft:seagrass',
  'sea_grass': 'minecraft:seagrass',
  'tallseagrass': 'minecraft:tall_seagrass',
  'chain': 'minecraft:chain',
  'iron_bars': 'minecraft:iron_bars',
  'brewing_stand': 'minecraft:brewing_stand',
  'cauldron': 'minecraft:cauldron',
  'compass': 'minecraft:compass',
  'clock': 'minecraft:clock',
  'recovery_compass': 'minecraft:recovery_compass',
  'goat_horn': 'minecraft:goat_horn',
  'spyglass': 'minecraft:spyglass',
  'brush': 'minecraft:brush',
  'air': 'minecraft:air',
  'cave_air': 'minecraft:cave_air',
  'void_air': 'minecraft:void_air',
  'moving_piston': 'minecraft:moving_piston',
  'light': 'minecraft:light',
  'sculk_sensor': 'minecraft:sculk_sensor',
  'calibrated_sculk_sensor': 'minecraft:calibrated_sculk_sensor',
  'sculk_catalyst': 'minecraft:sculk_catalyst',
  'sculk_shrieker': 'minecraft:sculk_shrieker',
  'ochre_froglight_top': 'minecraft:ochre_froglight',
  'verdant_froglight_top': 'minecraft:verdant_froglight',
  'pearlescent_froglight_top': 'minecraft:pearlescent_froglight',
  'ochre_froglight_side': 'minecraft:ochre_froglight',
  'verdant_froglight_side': 'minecraft:verdant_froglight',
  'pearlescent_froglight_side': 'minecraft:pearlescent_froglight',
};

function getAverageColor(imageData, width, height) {
  let r = 0, g = 0, b = 0, a = 0, total = 0;
  
  for (let y = 0; y < height; y++) {
    for (let x = 0; x < width; x++) {
      const idx = (y * width + x) * 4;
      const alpha = imageData[idx + 3];
      
      if (alpha > 0) {
        r += imageData[idx];
        g += imageData[idx + 1];
        b += imageData[idx + 2];
        a += alpha;
        total++;
      }
    }
  }
  
  if (total === 0) return null;
  
  return {
    r: Math.round(r / total),
    g: Math.round(g / total),
    b: Math.round(b / total),
    a: Math.round(a / total)
  };
}

async function processTextures() {
  const files = await readdir(TEXTURE_DIR);
  const pngFiles = files.filter(f => f.endsWith('.png') && !f.includes('_stage') && !f.includes('_on') && !f.includes('_lit'));
  
  const colorMap = new Map();
  const canvas = createCanvas(16, 16);
  const ctx = canvas.getContext('2d');
  
  console.log(`Processing ${pngFiles.length} texture files...`);
  
  for (const file of pngFiles) {
    const baseName = file.replace('.png', '').replace('.mcmeta', '');
    const blockName = BLOCK_NAME_MAPPING[baseName];
    
    if (!blockName) continue;
    
    try {
      const filePath = join(TEXTURE_DIR, file);
      const buffer = await readFile(filePath);
      const img = await loadImage(buffer);
      
      canvas.width = img.width;
      canvas.height = img.height;
      ctx.drawImage(img, 0, 0);
      
      const imageData = ctx.getImageData(0, 0, img.width, img.height);
      const color = getAverageColor(imageData.data, img.width, img.height);
      
      if (color) {
        const hexColor = (color.r << 16) | (color.g << 8) | color.b;
        
        if (!colorMap.has(blockName) || baseName.includes('top') || baseName === blockName.replace('minecraft:', '')) {
          colorMap.set(blockName, hexColor);
        }
      }
    } catch (e) {
      console.error(`Error processing ${file}: ${e.message}`);
    }
  }
  
  const output = `// Auto-generated block colors from textures
// Generated at ${new Date().toISOString()}

export const BLOCK_COLORS: Record<string, { color: number; grass?: boolean; foliage?: boolean; water?: boolean; alpha?: number }> = {
${Array.from(colorMap.entries())
  .map(([name, color]) => {
    let extra = '';
    if (name.includes('leaves') || name.includes('wart_block')) extra = ', foliage: true';
    else if (name.includes('grass_block') || name.includes('grass') && !name.includes('grass_block')) extra = ', grass: true';
    else if (name === 'minecraft:water') extra = ', water: true';
    return `  '${name}': { color: 0x${color.toString(16).padStart(6, '0')}${extra} }`;
  })
  .join(',\n')}
};

export function getBlockColor(blockName: string): number {
  const info = BLOCK_COLORS[blockName];
  return info ? info.color : 0xff00ff;
}

export function isGrassBlock(blockName: string): boolean {
  const info = BLOCK_COLORS[blockName];
  return info?.grass === true;
}

export function isFoliageBlock(blockName: string): boolean {
  const info = BLOCK_COLORS[blockName];
  return info?.foliage === true;
}

export function isWaterBlock(blockName: string): boolean {
  const info = BLOCK_COLORS[blockName];
  return info?.water === true;
}
`;
  
  await writeFile(OUTPUT_FILE, output);
  console.log(`Generated ${colorMap.size} block colors to ${OUTPUT_FILE}`);
}

processTextures().catch(console.error);
